중단어 프리셋 추가
asm6788/NamuPPuli pull request #1
Opened 2022-10-02 15:31 UTC by AuroraCaelum

- 대한민국 대통령
- 해외 정치인

2022-10-02 15:58 UTC, asm6788 commented
리드미 갱신도 부탁드립니다.

2022-10-02 15:58 UTC, asm6788 requested changes
리드미 갱신도 부탁드립니다.

2022-10-02 17:29 UTC, AuroraCaelum commented
리드미 갱신했습니다.

2022-10-02 17:53 UTC, asm6788 requested changes
.DS_Store 제거 부탁드립니다

2022-10-03 10:22 UTC, AuroraCaelum commented
> .DS_Store 제거 부탁드립니다

제거했습니다.

2022-10-03 10:23 UTC, asm6788 approved these changes

2022-10-03 11:10 UTC, merged